  server:
    type: simple
    connector:
      type: http
      port: 8080

  database:
    driverClass: com.mysql.jdbc.Driver
    user: Cyriel
    password: dfghjkytfg
    url: jdbc:mysql://mysql.stackcp.com:504/arcadeground

    properties:
      charSet: UTF-8

    maxWaitForConnection: 1s
    validationQuery: "SELECT 1"
    validationQueryTimeout: 3s
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
    evictionInterval: 10s
    minIdleTime: 1 minute

  cors:
      allowedHeaders: "*"
      allowedMethods: "X-Requested-With,Content-Type,Accept,Origin"
      allowedOrigins: "OPTIONS,GET,PUT,POST,DELETE,HEAD"

  jwt:
    author: "http://arcadegamegrounds.com"
    signature: "krabbel"